source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'YCStateButton_Example', :exclusive => true do
  pod "YCStateButton", :path => "../"
end

target 'YCStateButton_Tests', :exclusive => true do
  pod "YCStateButton", :path => "../"

  
end
